name: Update Posts from gilangvf.com.free

on:
  schedule:
    - cron: "0 */6 * * *"  # jalan tiap 6 jam
  workflow_dispatch:        # bisa manual dari GitHub Actions tab

jobs:
  update-posts:
    runs-on: ubuntu-latest
    permissions:
      contents: write       # agar bisa commit ke repo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install node-fetch@3 jsdom@24

      - name: Fetch latest posts
        run: node scripts/fetch.js

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add posts.json
          git diff --quiet && echo "No changes to commit" || git commit -m "Update posts.json"
          git push
