name: Google Ping

on:
  push:
    branches:
      - main  # atau 'master'

jobs:
  notify-google:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Google sitemap
        run: |
          echo "Ping Google untuk sitemap..."
          curl "http://www.google.com/ping?sitemap=https://gilangvf8-hash.github.io/sitemap.xml"
