name: IndexNow Sitemap Submission

on:
  push:
    branches:
      - main   # sesuaikan dengan branch GitHub Pages kamu (main/master)

jobs:
  submit-to-indexnow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract URLs from sitemap and submit to IndexNow
        run: |
          # Ganti sesuai URL sitemap kamu
          SITEMAP="https://gilangvf8-hash.github.io/sitemap.xml"
          API_KEY="77a3acba077848458350759957d374a1"

          # Ambil semua <loc> dari sitemap
          URLS=$(curl -s $SITEMAP | grep -oP '(?<=<loc>).*?(?=</loc>)')

          # Buat JSON array urlList
          URL_JSON=$(printf '"%s",' $URLS | sed 's/,$//')

          # Kirim ke IndexNow
          curl -H "Content-Type: application/json; charset=utf-8" -X POST "https://api.indexnow.org/IndexNow" -d "{
            \"host\": \"gilangvf8-hash.github.io\",
            \"key\": \"$API_KEY\",
            \"keyLocation\": \"https://gilangvf8-hash.github.io/$API_KEY.txt\",
            \"urlList\": [ $URL_JSON ]
          }"
